# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-02-07 23:06
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topic',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
